export const Constant = {
    sidebarnav: {
        dashboard: {
            name: 'Dashboard',
            shop: 'Shop',
            total: 'Total',
            commission : 'Commission',
            shopbalance: 'Shop Balance',
            sitebalance: 'Site Balance',
            paid : 'Paid',
            createdAt: 'Created At',
            latestRequestPayoutofSeller: 'Latest Request Payout of Seller',
            orders: 'Orders',
            products: 'Products',
            users: 'Users',
            shops: 'Shops',
            statistic: 'Statistic',
            featured: 'Featured',
            actived: 'Actived',
            inActived: 'InActived',
            verified: 'Verified',
            unverified: 'Unverified',
            totalSub: 'Total Sub',
            completed: 'Completed',
            shipping: 'Shipping',
            progressing: 'Progressing',
            pending: 'Pending',
            refunded: 'Refunded',
            cancelled: 'Cancelled',
            approved: 'Approved',
            rejected: 'Rejected'
        },
        users: {
            name: 'Users',
            listuser: {
                name: 'List users',
                namecol: 'Name',
                email: 'Email',
                role: 'Role',
                active: 'Active',
                emailVerified: 'Email Verified',
                createdAt:'Created at',
                actions: 'Actions',
                filter: 'Filter',
                username: 'Username'
            },
            createname:{
                name: 'Create New',
                firstandlastname: 'First and last name',
                pleaseenteruserfirstnameandlastname : 'Please enter user first name and last name',
                email:'Email',
                emailisrequired: 'Email is required',
                pleaseenteravalidemailaddress: 'Please enter a valid email address',
                active: 'Active',
                emailverified: 'Email verified',
                role: 'Role',
                user: 'User',
                admin: 'Admin',
                phonenumber: 'Phone number',
                address: 'Address',
                avatar: 'Avatar',
                createuserbeforeupdateavatar: 'Create user before update avatar',
                password: 'Password',
                pleaseenterpassword: 'Please enter password',
                passwordmustbeatleast6characters: 'Password must be at least 6 characters',
                save: 'Save',
                cancel: 'Cancel'
            },
            profilecard:{
                Emailaddress: 'Email address',
                Phone: 'Phone',
                Address: 'Address',
                SocialProfile: 'Social Profile',
                Created: 'Created',
                joinedat: 'joined at'
            }
        },
        shops: {
            name: 'Shops',
            listing: {
                name: 'Listing',
                nameCol: 'Name',
                Owner: 'Owner',
                Email: 'Email',
                Address: 'Address',
                Documentissue: 'Document issue',
                Featured: 'Featured',
                Verified: 'Verified',
                Active: 'Active',
                Featuredto: 'Featured to',
                Createdat: 'Created at',
                Actions: 'Actions',
                searching: 'searching',
                Sorrysuggestionscouldnotbeloaded: 'Sorry, suggestions could not be loaded',
                All: 'All',
                No: 'No',
                Yes: 'Yes',
                Filter: 'Filter',
                Thereisnoitemsyet: 'There is no shops yet',
            },
            shopcreate:{
                name: 'Shop Create',
                ShopName: 'Shop Name',
                Pleaseentershop: 'Please enter shop',
                Owner: 'Owner',
                searching: 'searching',
                Sorrysuggestionscouldnotbeloaded: 'Sorry, suggestions could not be loaded',
                Address: 'Address',
                Pleaseenteraddress: 'Please enter address',
                City: 'City',
                Pleaseentercity: 'Please enter city',
                State: 'State',
                Pleaseenterstate: 'Please enter state',
                Country: 'Country',
                Pleaseentercountry: 'Please enter country',
                Zipcode: 'Zip code',
                Pleaseenterzipcode: 'Please enter zip code',
                Email: 'Email',
                Pleaseenteremail: 'Please enter email',
                Phonenumber: 'Phone number',
                Pleaseenterphonenumber: 'Please enter phone number',
                VerificationIssue: 'Verification Issue',
                Save: 'Save',
                Cancel: 'Cancel',
                District: 'District',
                Ward: 'Ward'
            },
            shopUpdate:{
                list:{
                    BasicInfo: 'Basic Info',
                    BusinessInfo: 'Business Info',
                    SocialInfo: 'Social Info',
                    ShippingInfo: 'Shipping Info',
                },
                basicInfo:{
                    ShopName: 'Shop Name',
                    Pleaseentershopname: 'Please enter shop name',
                    ShopAlias: 'Shop Alias',
                    Owner: 'Owner',
                    Address: 'Address',
                    City: 'City',
                    State: 'State',
                    District: 'District',
                    Ward: 'Ward',
                    Country: 'Country',
                    Zipcode: 'Zip code',
                    Email: 'Email',
                    Phonenumber: 'Phone number',
                    ReturnAddress: 'Return Address',
                    HeaderText: 'Header Text',
                    Announcement: 'Announcement',
                    Googleanyalyticscode: 'Google anyalytics code',
                    Logo: 'Logo',
                    VerificationIssue: 'Verification Issue',
                    Banner: 'Banner',
                    Activated: 'Activated',
                    Verified: 'Verified',
                    Featured: 'Featured',
                    Save: 'Save',
                    Cancel: 'Cancel'
                },
                businessInfo: {
                    BusinessName: 'Business Name',
                    Identifier: 'Identifier',
                    Address: 'Address',
                    Save: 'Save',
                    Cancel: 'Cancel'
                },
                socialInfo:{
                    Pleaseentervalidurl: 'Please enter valid url',
                    Verified: 'Verified',
                    Save: 'Save',
                    Cancel: 'Cancel'
                },
                shippingInfo:{
                    DefaultPrice: 'Default Price',
                    Thisfieldisrequired: 'This field is required',
                    PriceForEachProductQuantity: 'Price For Each Product Quantity',
                    ShipFrom: 'Ship From',
                    ProcessingTimeInDay: 'Processing Time In Day',
                    Onetothreeworkingdays: 'One to three working days',
                    Fourtofiveworkingdays: 'Four to five working days',
                    Fivetoeightworkingdays: 'Five to eight working days',
                    Other: 'Other',
                    ShippingPolicy: 'Shipping Policy',
                    RefundPolicy: 'Refund Policy',
                    Address: 'Address',
                    City: 'City',
                    District: 'District',
                    Ward: 'Ward',
                    ZipCode: 'Zip Code',
                    Save: 'Save',
                    Cancel: 'Cancel',
                },
                notificationInfo:{
                    LowInventory: 'Low Inventory',
                    Save: 'Save',
                    Cancel: 'Cancel'
                },
                bankInfo:{
                    BankName: 'Bank Name',
                    Pleaseenterbankname: 'Please enter bank name',
                    PleaseenterbankID: 'Please enter bank ID',
                    BankBranchName: 'Bank Branch Name',
                    Pleaseenterbankbranchname: 'Please enter bank branch name',
                    BankBranchID: 'Bank Branch ID',
                    PleaseenterbankbranchID: 'Please enter bank branch ID',
                    AccountName: 'Account Name',
                    Pleaseenteraccountname: 'Please enter account name',
                    AccountNumber: 'Account Number',
                    Pleaseenteraccountnumber: 'Please enter account number',
                    AccountNumberisalphanumericcharacters: 'Account Number is alphanumeric characters',
                    AccountNumbermustbeatleast11characters: 'Account Number must be at least 11 characters',
                    SwiftCode: 'Swift Code',
                    Pleaseenterswiftcode: 'Please enter swift code',
                    SwiftCodeisalphanumericcharacters: 'Swift Code is alphanumeric characters',
                    SwiftCodemustbe8or11characters: 'Swift Code must be 8 or 11 characters',
                    Save: 'Save'
                },
                couponInfo:{
                    Name:'Name',
                    Code: 'Code',
                    DiscountPercentage: 'Discount Percentage',
                    Limit: 'Limit',
                    ExpiredTime: 'Expired Time',
                    CreatedAt: 'Created At',
                    Unlimited: 'Unlimited',
                }
            },
        },
        products: {
            name: 'Products',
            listing: {
                Image: 'Image',
                Name: 'Name',
                Category: 'Category',
                Shop: 'Shop',
                Feature: 'Feature',
                Hot: 'Hot',
                BestSell: 'Best Sell',
                Type: 'Type',
                DailyDeal: 'Daily Deal',
                Active: 'Active',
                ShopVerified: 'Shop Verified',
                Createdat: 'Created at',
                Actions: 'Actions',
                Search: 'Filter',
                Physical: 'Physical',
                Digital: 'Digital',
                Status: 'Status',
                SAP: 'SAP',
                Producer: 'Producer'
            },
            variants:{
                Key: 'Key',
                DisplayText: 'Display Text',
                Nameofvariant: 'Name of variant',
                Value: 'Value',
                Valueofvariant: 'Value of variant',
                Price: 'Price',
                SalePrice: 'Sale Price',
                StockQuantity: 'Stock Quantity',
                Updatedat: 'Updated at',
                Actions: 'Actions',
                Add: 'Add',
                Thereisnovariant: 'There is no variant, please create new',
                Addnew: 'Add new',
                Usethesesystemoptionsorcustomitbyyourself: 'Use these system options or custom it by yourself',
                Option: 'Option'
            },
            updatevariants:{
                Updatevariant:'Update variant',
                DigitalFile: 'Digital File',
                Price: 'Price',
                SalePrice: 'Sale Price',
                Stockquantity: 'Stock quantity',
                Update: 'Update'
            },
            productcreate:{
                name: 'Product Create',
                Information: 'Information',
                Specifications: 'Specifications',
                Images:'Images',
                Variants: 'Variants',
                Reviews: 'Reviews',
                Name: 'Name',
                Alias: 'Alias',
                Ifthealiasisexist: 'If the alias is exist, the system automatically adds any character at the end of alias',
                Type: 'Type',
                Physical: 'Physical',
                Digital: 'Digital',
                DigitalFilePath: 'Digital FilePath',
                StockQuantity: 'Stock Quantity',
                Seller: 'Seller',
                searching:'searching',
                Sorrysuggestionscouldnotbeloaded:'Sorry, suggestions could not be loaded',
                Price: 'Price',
                SalePrice: 'Sale Price',
                TaxName: 'Tax Name',
                TaxValue:'Tax Value',
                RestrictCODareas: 'Restrict COD areas',
                Add: 'Add',
                Shortdescription: 'Short description',
                Description: 'Description',
                Category: 'Category',
                Nocategory: 'No category',
                Metakeywords: 'Meta keywords',
                Metadescription: 'Meta description',
                Enterzipcode: 'Enter zip code or select the free ship areas',
                ZipCode: 'Zip Code',
                FreeShipCountry: 'Free Ship Country',
                FreeShipState: 'Free Ship State',
                FreeShipCity: 'Free Ship City',
                Dailydeal: 'Daily deal',
                DealTo: 'Deal To',
                FreeShip: 'Free Ship',
                Featured: 'Featured',
                HotProduct: 'Hot Product',
                BestSelling: 'Best Selling',
                Active: 'Active',
                Clicktosetmainimage: 'Click to set main image',
                Pleasecreateproductthenaddvariants: 'Please create product then add variants',
                Pleasecreateproduct: 'Please create product',
                Submit: 'Save',
                Cancel: 'Cancel',
                Weight: 'Weight',
                TradeDiscount: 'Trade Discount',
                WeightCondition: 'Weight (minimum 100g)',
                MarketingDiscount: 'Marketing Discount',
                BuyerDiscount: "Buyer Discount",
                GoldTimeDiscount: "Gold Time Discount",
                Deny: "Deny",
                Cause: "Cause",
                SAP: "SAP",
                NTDPrice: "NTD Price",
                NTDUnit: "NTD Unit",
                WEPrice: "WE Price",
                WEUnit: "WE Unit",
                Lang: "Lang",
                SKU: "SKU",
                PackageMethod: "Package Method",
                Producer: "Producer",
                Expiry: "Expiry",
                Country: "Country",
                Ingredient: "Ingredient",
                isPromotion: "isPromotion"
            },
            productcategories:{
                name: 'Products categories',
                namCol: 'Name',
                Children: 'Children',
                CreatedAt: 'CreatedAt',
                Actions: 'Actions',

            },
            createnewcategory:{
                name: 'Create new category',
                nameCol: 'Name',
                Alias: 'Alias',
                Description: 'Description',
                Parent: 'Parent',
                Noparen: 'No parent',
                Image: 'Image',
                Metakeywords: 'Meta keywords',
                Metadescription: 'Meta description',
                Submit: 'Save',
                Cancel: 'Cancel'
            },
            productoption:{
                name: 'Products options',
                namCol: 'Name',
                Description: 'Description',
                Createdat: 'Created at',
                Actions: 'Actions'

            },
            createnewoption:{
                name: 'Create new option',
                nameCol: 'Name',
                Description: 'Description',
                Key: 'Key',
                Options: 'Options',
                Displaytext: 'Display text',
                Create: 'Create',
                Submit: 'Submit'
            },
            updateoption:{
                name: 'Create new option',
                nameCol: 'Name',
                Description: 'Description',
                Key: 'Key',
                Options: 'Options',
                Displaytext: 'Display text',
                Create: 'Create',
                Submit: 'Submit'
            }

        },
        events:{
          name: 'Event name',
          listing: {
            name: 'Event Listing'
          },
          importlisting: {
            name: 'Event Import Listing'
          },
          slot: {
            name: 'Event Slot'
          },
          awardlisting: {
            name: 'Award Listing'
          }
        },
        orders: {
            name: 'Orders',
            listing: {
                Order:'Order',
                TotalProducts: 'Total Products',
                Totalprice: 'Total price',
                Paymentmethod: 'Payment method',
                UserIP: 'User IP',
                CreatedAt: 'Created At'

            },
            refund: {
                name: 'Refunds',
                Product: 'Product',
                Reason: 'Reason',
                Createdat: 'Created at',
                Actions: 'Actions'
            },
            view:{
                Generalinformation: 'General information',
                Number: 'Number',
                IP: 'IP',
                Createdat: 'Created at',
                Shippingaddress: 'Shipping address',
                Paymentmethod: 'Payment method',
                Paymentstatus: 'Payment status',
                Totalprice: 'Total price',
                Shippingdetails: 'Shipping details',
                Name: 'Name',
                Email: 'Email',
                Phonenumber: 'Phone number',
                Streetaddress: 'Street address',
                City: 'City',
                State: 'State',
                Country: 'Country',
                Products: 'Products',
                Product: 'Product',
                Quantity: 'Quantity',
                Status: 'Status',
                Tax: 'Tax',
                Shippingprice: 'Shipping price',
                Price: 'Price',
                Commission: 'Commission',
                CommissionPrice: 'Commission Price',
                Balance: 'Balance',
                Completed: 'Completed',
                Shipping: 'Shipping',
                Pending: 'Pending',
                Progressing: 'Progressing',
                Refunded: 'Refunded',
                Cancelled: 'Cancelled',
                UpdateStatus: 'Update Status',
                Cancel: 'Cancel',
                District: 'District',
                Ward: 'Ward',
                FeeShip: 'FeeShip'
            }
        },
        banners: {
            name: 'Banners',
            listing: {
                Title: 'Title',
                Content: 'Content',
                Position: 'Position',
                Link: 'Link',
                Createdat: 'Created at',
                Actions: 'Actions'
            },
            newbanner:{
                name: 'New banner',
                Title: 'Title',
                Content: 'Content',
                Image: 'Image',
                Link: 'Link',
                Position: 'Position',
                Default: 'Default',
                Submit: 'Save',
                Cancel: 'Cancel',
                isActive: 'Active'
            }
        },
        posts: {
            name: 'CMS',
            listing:{
                postname: 'Listing Post',
                pagename: 'Listing Page',
                Title: 'Title',
                Alias: 'Alias',
                Content: 'Content',
                Createdat: 'Created at',
                Actions: 'Actions',
                Clickedittoviewcontent: 'Click edit to view content',
                Category: 'Category',
                Filter: 'Filter',
                Active: 'Active'
            },
            createPosts:{
                name: 'Create Post',
                Title: 'Title',
                Alias: 'Alias',
                Content: 'Content',
                Submit: 'Save',
                Cancel: 'Cancel',
                Description: 'Desc',
                Active: 'Active',
                MainSet: 'Set Main Page',
                Category: 'Category',
                // All: "All",
                // Notification: "Notification all"
            }
        },
        newsletter: {
            name: 'Newsletter',
            contacts:{
                name: 'Contacts',
                Email: 'Email',
                Name: 'Name',
                Createdat: 'Created at',
                Search: 'Search'
            },
            sendmail:{
                name: 'Sendmail',
                Subject: 'Subject',
                Subjectisrequired: 'Subject is required',
                Usertype:'User type',
                Allusers: 'All users',
                Seller: 'Seller',
                Registereduser:'Registered user',
                Newslettercontacts: 'Newsletter contacts',
                Content:'Content',
                Contentisrequired:'Content is required',
                Send:'Send',
                Cancel:'Cancel'
            }
        },
        complaints: {
            name: 'Complaints',
            listing:{
                name: 'Listing',
                User: 'User',
                UserType: 'User Type',
                Content: 'Content',
                Status: 'Status',
                Createdat: 'Created at',
                Actions: 'Actions',
                Seller:'Seller',
                Pending: 'Pending',
                Resolved: 'Resolved',
                Rejected: 'Rejected',
                Clickedittoviewcontent:'Click edit to view content',
            },
            createComplaints: {
                Content: 'Content',
                Note: 'Note',
                Status: 'Status',
                Pending: 'Pending',
                Resolved: 'Resolved',
                Rejected: 'Rejected',
                Submit: 'Submit',
                Cancel: 'Cancel'
            }
        },
        commission: {
            name: 'Commission',
            listing: {
                name: 'Listing',
                From: 'From',
                To: 'To',
                Shop: 'Shop',
                searching: 'searching',
                Sorrysuggestionscouldnotbeloaded: 'Sorry, suggestions could not be loaded',
                FilterStats: 'Filter Stats',
                Pending: 'Pending',
                Approved: 'Approved',
                Commission: 'Commission',
                ShopBalance: 'Shop Balance',
                SiteBalance: 'Site Balance',
                RequestID: 'Request ID',
                Total: 'Total',
                Paid: 'Paid',
                CreatedAt: 'Created At',
                Actions: 'Actions',
                Rejected: 'Rejected'
            }
        },
        requestspayout: {
            name: 'Requests Payout',
            listing: {
                name: 'Listing',
                From: 'From',
                To: 'To',
                Shop: 'Shop',
                searching: 'searching',
                Sorrysuggestionscouldnotbeloaded: 'Sorry, suggestions could not be loaded',
                FilterStats: 'Filter Stats',
                Pending: 'Pending',
                Approved: 'Approved',
                Commission: 'Commission',
                ShopBalance: 'Shop Balance',
                SiteBalance: 'Site Balance',
                RequestID: 'Request ID',
                Total: 'Total',
                Paid: 'Paid',
                CreatedAt: 'Created At',
                Actions: 'Actions',
                Rejected: 'Rejected'
            }
        },
        report: {
            name: 'Sale',
            sales:{
                name: 'Sale managerment',
                Shop: 'Shop',
                Totalorder: 'Total order',
                TotalProduct: 'Total Product',
                TotalPrice: 'Total Price',
                Commission:'Commission',
                Earning:'Earning',
                Tax:'Tax',
                RecieverCommission: 'Reciever Commission',
            },
            payout:{
                name: 'Payout',
                Shop:'Shop',
                Approved:'Approved',
                Paid:'Paid',
                Pendingrequest:'Pending request',
                CurrentCODbalance:'Current COD balance',
                CurrentNonCODbalance:'Current Non COD balance',
                Currentbalancesummary: 'Current balance summary',
                Shopearning:'Shop earning',
                Siteearning:'Site earning',
                Commission:'Commission',
                Total: 'Total',
                Sitemustpay: 'Site must pay',
                Shopmustpay: 'Shop must pay'
            }
        },
        kpi: {
            name: 'Kpi',
            list:{
                name: 'List Kpi Payment',
                Title: 'Title',
                Alias: 'Alias',
                Content: 'Content',
                Submit: 'Save',
                Cancel: 'Cancel',
                Description: 'Desc',
                Active: 'Active',
                MainSet: 'Set Main Page',
                Category: 'Category'
            },
            config:{
                name: 'Config KPI',
                Title: 'Title',
                Alias: 'Alias',
                Content: 'Content',
                Submit: 'Save',
                Cancel: 'Cancel',
                Description: 'Desc',
                Active: 'Active',
                MainSet: 'Set Main Page',
                Category: 'Category'
            },
        },
        config: {
            name: 'Config',
            nameCol: 'Name',
            Value: 'Value',
            Save: 'Save',
            Username: 'Username',
            Password: 'Password',
            Signature: 'Signature',
            Sandbox: 'Sandbox',
            AccountNumber: 'Account Number',
            SubaccountNumber:'Sub account Number',
            Salt:'Salt',
            Flexformsubscriptionid:'Flexform subscription id',
            Flexformsinglepaymentid: 'Flexform single payment id',
            Keywords:'Keywords',
            Description:'Description',
            Icon:'Icon',
            Title:'Title',
            Displaytext:'Display text',
            Cashondelivery:'Cash on delivery',
            item:{
                Sitename : 'Site name',
                Sitefavicon: 'Site favicon',
                Contactemail: 'Contact email',
                SEOmetadataforhomepage: 'SEO meta data for home page',
                Publiccontactphonenumber: 'Public contact phone number',
                Publiccontactemail: 'Public contact email',
                Sociallinks: 'Social links',
                Paymentgatewayconfig: 'Payment gateway config',
                Sitecommission: 'Site commission',
                Customcodebeforeendheadtag: 'Custom code before end head tag',
                Sitelogo: 'Site logo',
                Customcodebeforeendbodytag: 'Custom code before end body tag',
            },
            languages:{
                name: 'Languages',
                Key: 'Key',
                nameCol: 'Name',
                Default:'Default',
                Active:'Active',
                Createdat:'Created at',
                Addnew:'Add new',

                AddNewLanguage: "Add new language",
                SelectLanguages: "Select languages",
                LanguageRequired: "Language key is required",
                NameRequired: "Name is required",
                Create: "Create",
            },
            translations:{
                Text:'Text',
                Translation:'Translation',
                Pulltext: 'Pull text',
                Update:'Update',
                Search:'Search',

            },
            text:{
                name: 'Text',
                Text:'Text',
                Createdat: 'Created at',
                Search:'Search',
                Add:'Add'
            }
        },
        promotions:{
            name: 'Promotion',
            listing:{
                name: 'Promotion listing'
            },
            create: {
                name: 'Promotion create'
            },
            programList: {
                name: 'Type of program'
            },
            programDetail: {
                name: 'Create program'
            }
        },
        packages: {
            name: 'Packages',
            packgelisting:{
                Name:'Name',
                Price:'Price',
                Duration:'Duration',
                CreatedAt:'Created At',
                Action:'Action',
                Filter:'Filter',
                Days:'Days'
            },
            packagecreate:{
                name: 'Package Create',
                nameCol: 'Name',
                Pleaseenterpackagename: 'Please enter package name',
                Price: 'Price',
                Pleaseenterpackageprice: 'Please enter package price',
                Duration: 'Duration',
                Durationofthepackageinday: 'Duration of the package in day',
                Pleaseenterpackageduration: 'Please enter package duration',
                Description: 'Description',
                Pleaseenterpackagedescription: 'Please enter package description',
                Submit: 'Submit'
            },
            packagepaymenthistory:{
                name: 'Package Payment History',
                SellerName: 'Seller Name',
                Packagename: 'Package name',
                PaymentGateway: 'Payment Gateway',
                Price: 'Price',
                TransactionId:'Transaction Id',
                CreatedAt: 'Created At',
                Thereisnoitemsyet: 'There is no items yet',
            }
        },
        myprofile: {
            name: 'My Profile',
            Firstandlastname: 'First and last name',
            Pleaseenteruserfirstnameandlastname:'Please enter user first name and last name',
            Email:'Email',
            Emailisrequired:'Email is required',
            Pleaseenteravalidemailaddress:'Please enter a valid email address',
            Active: 'Active',
            Emailverified:'Email verified',
            Role:'Role',
            User:'User',
            Admin: 'Admin',
            Phonenumber:'Phone number',
            Address:'Address',
            Password:'Password',
            Passwordmustbeatleast6characters: 'Password must be at least 6 characters',
            Blanktokeepcurrentpassword: 'Blank to keep current password',
            Avatar: 'Avatar',
            Save: 'Save',
            Cancel: 'Cancel',
            logout:{
                name: 'Logout'
            },
            history:{
                ActionHistory: 'Action History',
                CreatedAt: 'Created At',
                Username: 'Username',
                Action: 'Action',
                Description: 'Description',
                Filter: 'Filter',
                Time: 'Time',
                Create: 'Create',
                Edit: 'Edit',
                Delete: 'Delete'
            }
        },
        upload: {
          image: {
            DropOrClickSelectImage: 'Drop or click to select file',
            MediaManager: 'Media manager',
            Library: 'Library',
            Upload: 'Upload',
            Name: 'Name',
            Description: 'Description',
            Search: 'Search',
            URL: 'URL',
            FileName: 'File name',
            FileNameRequired: 'File name is required',
            FileDescription: 'File description',
            Update: 'Update',
            Select: 'Select',
            Browse: 'Browse',
          }
        },
        userids: {
        name: 'Notification',
        listing: {
          Title: 'Title',
          Content: 'Content',
          Position: 'Position',
          Link: 'Link',
          Createdat: 'Created at',
          Actions: 'Actions'
        },
        newuser:{
          name: 'Create New Notification',
          Title: 'Title',
          Content: 'Content',
          User: 'User',
          Submit: 'Save',
          Cancel: 'Cancel',
        }
      },
    },
    error:{
        delete:{
           title: 'Are you sure want to delete this item?',
           sucess: 'Item has been deleted!',
           unsucess:'Something went wrong, please try again!',
        }
    }
};

export const enumConstant = {
    unit: {
        bag: 'Túi',
        package: 'Bịch',
        box: 'Hộp'
    }
}
